// <auto-generated />
using System;
using DrawingApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DrawingApp.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251206091247_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.11");

            modelBuilder.Entity("DrawingApp.Core.Entities.BoardShape", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("BoardId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("DashStyle")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FillColor")
                        .HasColumnType("TEXT");

                    b.Property<string>("GeometryJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ShapeType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StrokeColor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Thickness")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("BoardId");

                    b.ToTable("BoardShapes");
                });

            modelBuilder.Entity("DrawingApp.Core.Entities.DrawingBoard", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("BackgroundColor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<double>("Height")
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProfileId")
                        .HasColumnType("TEXT");

                    b.Property<double>("Width")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("ProfileId");

                    b.ToTable("Boards");
                });

            modelBuilder.Entity("DrawingApp.Core.Entities.Profile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<double>("DefaultBoardHeight")
                        .HasColumnType("REAL");

                    b.Property<double>("DefaultBoardWidth")
                        .HasColumnType("REAL");

                    b.Property<string>("DefaultStrokeColor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("DefaultStrokeDash")
                        .HasColumnType("INTEGER");

                    b.Property<double>("DefaultStrokeThickness")
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Theme")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Profiles");
                });

            modelBuilder.Entity("DrawingApp.Core.Entities.ShapeTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("DashStyle")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FillColor")
                        .HasColumnType("TEXT");

                    b.Property<string>("GeometryJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<int>("ShapeType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StrokeColor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Thickness")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("Templates");
                });

            modelBuilder.Entity("DrawingApp.Core.Entities.BoardShape", b =>
                {
                    b.HasOne("DrawingApp.Core.Entities.DrawingBoard", "Board")
                        .WithMany("Shapes")
                        .HasForeignKey("BoardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Board");
                });

            modelBuilder.Entity("DrawingApp.Core.Entities.DrawingBoard", b =>
                {
                    b.HasOne("DrawingApp.Core.Entities.Profile", "Profile")
                        .WithMany("Boards")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("DrawingApp.Core.Entities.DrawingBoard", b =>
                {
                    b.Navigation("Shapes");
                });

            modelBuilder.Entity("DrawingApp.Core.Entities.Profile", b =>
                {
                    b.Navigation("Boards");
                });
#pragma warning restore 612, 618
        }
    }
}
